# Generated by Django 5.1.4 on 2025-03-08 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2W', 'Two Wheeler'), ('4W', 'Four Wheeler'), ('HV', 'Heavy Vehicle'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
